In [1]:
inp = open('8.txt','r').readlines()

In [2]:
import re
lst = []
for num in inp:
    lst.append((re.sub('\n','',num)))

In [ ]:
# lst

In [3]:
import numpy as np
arr_tst = np.zeros((99,99))
for i in range(len(lst)):
    for j in range(len(lst[0])):
        arr_tst[i][j]=int(lst[i][j])
arr_tst

array([[2., 0., 1., ..., 0., 1., 1.],
       [2., 2., 1., ..., 0., 2., 1.],
       [1., 0., 2., ..., 0., 1., 2.],
       ...,
       [0., 2., 1., ..., 1., 1., 2.],
       [0., 0., 2., ..., 2., 2., 2.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [5]:
# arr_tst = arr_tst.astype(int)

In [4]:
# PART 1
count = 0
for i in range(1,98):
    for j in range(1,98):
        if (False not in (arr_tst[i,j]>arr_tst[i,(j+1):])) or (False not in (arr_tst[i,j]>arr_tst[(i+1):,j])) or (False not in (arr_tst[i,j]>arr_tst[i,:j])) or (False not in (arr_tst[i,j]>arr_tst[:i,j])):
            count+=1
count

1390

In [5]:
4*99-4+1390

1782

In [6]:
# PART 2

import numpy as np
ss = 0
down = []
right = []
up = []
left = []
for x in range(1,98):
    for y in range(1,98):
        try:
            up.extend([min([i for i, b in enumerate(arr_tst[x,y]>arr_tst[:x,y][::-1]) if not b])])
#             print(arr_tst[x,y]>arr_tst[:x,y][::-1])
        except:
            up.extend([max([i for i, b in enumerate(arr_tst[x,y]>arr_tst[:x,y][::-1]) if b])])
        try:
            down.extend([min([t for t, u in enumerate(arr_tst[x,y]>arr_tst[(x+1):,y]) if not u])])
#             print(arr_tst[x,y]>arr_tst[(x+1):,y],x,y,arr_tst[x,y],arr_tst[(x+1):,y])
#             print(arr_tst[(x+1):,y])
        except:
            down.extend([max([t for t, u in enumerate(arr_tst[x,y]>arr_tst[(x+1):,y]) if u])])
            
        try:
            left.extend([min([i for i, b in enumerate(arr_tst[x,y]>arr_tst[x,:y][::-1]) if not b])])
#             print(arr_tst[x,:y][::-1])
    #             print(arr_tst[x,y]>arr_tst[x,:y][::-1])
        except:
            left.extend([max([i for i, b in enumerate(arr_tst[x,y]>arr_tst[x,:y][::-1]) if b])])
        try:
            right.extend([min([i for i, b in enumerate(arr_tst[x,y]>arr_tst[x,(y+1):]) if not b])])
#             print((arr_tst[x,y]>arr_tst[x,(y+1):]),x,y,arr_tst[x,y],arr_tst[x,(y+1):])
        except:
            right.extend([max([i for i, b in enumerate(arr_tst[x,y]>arr_tst[x,(y+1):]) if b])])
#             print((arr_tst[x,y]>arr_tst[x,(y+1):]),x,y,arr_tst[x,y],arr_tst[x,(y+1):])

print((np.array(up)+1),(np.array(right)+1),(np.array(down)+1),(np.array(left)+1))
s = (np.array(up)+1)*(np.array(right)+1)*(np.array(down)+1)*(np.array(left)+1)
print(s)
max(s)

[1 1 1 ... 1 2 3] [3 1 1 ... 1 1 1] [3 1 1 ... 1 1 1] [1 1 1 ... 1 1 1]
[9 1 1 ... 1 2 3]


474606

Testing

In [ ]:
tst = [
'30373',
'25512',
'65332',
'33549',
'35390'
]

In [ ]:
import numpy as np
arr_tst = np.zeros((5,5))
for i in range(len(tst)):
    for j in range(len(tst[0])):
        arr_tst[i][j]=int(tst[i][j])
arr_tst

In [ ]:
arr_tst = arr_tst.astype(int)

In [ ]:
arr_tst

In [ ]:
False not in (arr_tst[2,2]>arr_tst[2,3:])  # right for (i,j) -> (i,j+1:) ; left for (i,j) -> (i,:j)
# arr_tst[2,3:]

In [ ]:
# False in (arr_tst[2,1]>arr_tst[2,2:])  # down for (i,j) -> (i+1:,j) ; up for (i,j) -> (:i,j)
arr_tst[3:,2]

In [ ]:
len(lst[0])